# configuration for https://beets.io
# https://beets.readthedocs.io/en/stable/reference/config.html
#
# To install `beets` on macOS:
#
# $ brew install uv
# $ uv tool install beets --with requests --with certifi

# Store music library in ~/Documents/music, which is on iCloud
directory: ~/Documents/music

# https://beets.readthedocs.io/en/stable/plugins/index.html
#
# https://beets.readthedocs.io/en/stable/plugins/embedart.html
# https://beets.readthedocs.io/en/stable/plugins/fetchart.html
# https://beets.readthedocs.io/en/stable/plugins/fish.html
# https://beets.readthedocs.io/en/stable/plugins/info.html
# https://beets.readthedocs.io/en/stable/plugins/musicbrainz.html
plugins: embedart fetchart fish info musicbrainz
